{
 "title": "Connect Sandbox",
 "tags": [
  "Strimzi",
  "Kafka",
  "Kafka Connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_connect_worker_connector_count{strimzi_io_kind=~\"KafkaConnect.*\"})"
   },
   {
    "name": "strimzi_connect_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_connect_worker_connector_count{namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"})"
   }
  ]
 },
 "panels": [
  { "title": "Client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection creation total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connection_creation_total"
    }
   ]
  },
  {
   "title": "Incoming bytes total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_total"
    }
   ]
  },
  {
   "title": "IO ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_io_ratio" }
   ]
  },
  {
   "title": "I/O time ns avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_io_time_ns_avg" }
   ]
  },
  {
   "title": "IO Wait ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_io_wait_ratio" }
   ]
  },
  {
   "title": "IO wait time ns avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_io_wait_time_ns_avg"
    }
   ]
  },
  {
   "title": "Network I/O total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_network_io_total" }
   ]
  },
  {
   "title": "Request total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_request_total" }
   ]
  },
  {
   "title": "Request size average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_request_size_avg" }
   ]
  },
  {
   "title": "Response total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_response_total" }
   ]
  },
  {
   "title": "Select total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_select_total" }
   ]
  },
  {
   "title": "Source task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source record write total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_write_total"
      }
     ]
    },
    {
     "title": "Source record write rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_write_rate"
      }
     ]
    },
    {
     "title": "Source record poll total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_poll_total"
      }
     ]
    },
    {
     "title": "Source record poll rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_poll_rate"
      }
     ]
    },
    {
     "title": "Source record active count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_active_count"
      }
     ]
    },
    {
     "title": "Poll batch avg time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_poll_batch_avg_time_ms"
      }
     ]
    },
    {
     "title": "poll batch max time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_poll_batch_max_time_ms"
      }
     ]
    }
   ]
  },
  {
   "title": "Connect Worker metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connector startup attempts total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_connector_startup_attempts_total"
      }
     ]
    },
    {
     "title": "Connector startup success total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_connector_startup_success_total"
      }
     ]
    },
    {
     "title": "Connector startup failure total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_connector_startup_failure_total"
      }
     ]
    },
    {
     "title": "Task startup attempts total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_task_startup_attempts_total"
      }
     ]
    },
    {
     "title": "Task startup success total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_task_startup_success_total"
      }
     ]
    },
    {
     "title": "Task startup failure total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_task_startup_failure_total"
      }
     ]
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_status"
      }
     ]
    },
    {
     "title": "Task pause ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 2, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_pause_ratio"
      }
     ]
    },
    {
     "title": "Task running ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_running_ratio"
      }
     ]
    },
    {
     "title": "Batch size avg",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_avg"
      }
     ]
    },
    {
     "title": "Offset commit avg time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 2, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms"
      }
     ]
    },
    {
     "title": "Offset commit max time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_offset_commit_max_time_ms"
      }
     ]
    },
    {
     "title": "Batch size max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_max"
      }
     ]
    }
   ]
  },
  {
   "title": "Connector metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_connector_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})"
      }
     ]
    },
    {
     "title": "(Sink/Consumers) Incoming bytes per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_incoming_byte_total{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}[1m])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "(Source/Producers) Outgoing bytes per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_outgoing_byte_total{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}[1m])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_connect_cluster_name-connect-.+\",container=\"$strimzi_connect_cluster_name-connect\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum (jvm_memory_bytes_used{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percent", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}[5m])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "graph",
     "description": "JVM thread count",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connector task state with issues",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_connector_paused_task_count{namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (connector) != 0",
       "legendFormat": "[paused] {{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_failed_task_count{namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (connector) != 0",
       "legendFormat": "[failed] {{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (connector) != 0",
       "legendFormat": "[unassigned] {{connector}}"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}) by (connector) != 0",
       "legendFormat": "[destroyed] {{connector}}"
      }
     ]
    },
    {
     "title": "Connector task state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Number of connector tasks" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_connector_running_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "running"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_paused_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "paused"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_failed_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "unassigned"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "destroyed"
      }
     ]
    },
    {
     "title": "Connection count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_connection_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "#consumer connections"
      },
      {
       "expr": "sum(kafka_producer_connection_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "#producer connections"
      },
      {
       "expr": "sum(kafka_admin_client_connection_count{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})",
       "legendFormat": "#admin connections"
      }
     ]
    },
    {
     "title": "Connector Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "count by (status, connector) (kafka_connect_connector_status{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})"
      }
     ]
    },
    {
     "title": "Connector Task Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "count by (connector, task, status) (kafka_connect_connector_task_status{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"})"
      }
     ]
    }
   ]
  }
 ]
}