{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values "strimzi-kafka-operator"  "image" "imagePullSecrets" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}