{{- if .Values.connect.build -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connect.build.output.pushSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePushSecret" . }}
{{- end }}